# Generated by Django 2.0.2 on 2018-02-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ape_pat', models.CharField(max_length=50)),
                ('ape_mat', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=None, to='personal.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='unidad',
            field=models.ForeignKey(on_delete=None, to='personal.Unidad'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidad',
            field=models.ForeignKey(on_delete='CASCADE', to='personal.Unidad'),
        ),
    ]
